RPass="<%=cypher.read('secret/mariaDBRootPass')%>"
CIPass="<%=cypher.read('secret/cloudinit')%>"
SCRMDb="<%=customOptions.databaseNameSCRM%>"
SCRMUser="<%=customOptions.databaseUserSCRM%>"
SCRMPass="<%=customOptions.databasePassSCRM%>"
MYSQL_HOST="<%=evars.CUSTOM_MARIADB_IP%>"
PHP_VERSION="8.1"
MARIADB_VERSION="mariadb-10.11"
IP="<%=server.InternalIp%>"

echo "Printing Vars"
echo $RPass
echo $CIPass
echo $SCRMDb
echo $SCRMUser
echo $SCRMPass
echo $MYSQL_HOST

#Wait until any apt-get processes have finished
if [ `ps -ef | grep [a]pt-get | wc -l` = !0 ]
then
	echo "sleep for 120"
	sleep 120
fi

#Install sshpass and apache, start service and enable on boot
echo "Installing software"
apt-get install sshpass -y
apt-get install apache2 -y
systemctl stop apache2.service
systemctl start apache2.service
systemctl enable apache2.service

#Use sshpass to remotely execute mysql commands on DB server to create database and database user
echo "Running sshpass"
sshpass -p $CIPass ssh -oStrictHostKeyChecking=no -t morpheusci@$MYSQL_HOST <<REMOTE
sudo -S <<< "$CIPASS" mysql -u root -p$RPass -e "CREATE DATABASE $SCRMDb;"
sudo -S <<< "$CIPASS" mysql -u root -p$RPass -e "CREATE USER '$SCRMUser'@'$IP' IDENTIFIED BY '$SCRMPass';"
sudo -S <<< "$CIPASS" mysql -u root -p$RPass -e "GRANT ALL ON $SCRMDb.* TO $SCRMUser@'$IP' IDENTIFIED BY '$SCRMPass';"
sudo -S <<< "$CIPASS" mysql -u root -p$RPass -e "FLUSH PRIVILEGES;"
REMOTE

#Configure the database
#Quoting LAMP_USER_PASSWORD as password is autogenerated by Morpheus Cypher and could contain special characters
#sshpass -p $CIPASS ssh -oStrictHostKeyChecking=no -t morpheusci@$MYSQL_HOST <<REMOTE
#sudo -S <<< "$CIPASS" touch /tmp/pete
#sudo -S <<< "$CIPASS" mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE lamp_database;"
#sudo -S <<< "$CIPASS" mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE USER 'lamp_user'@'%' IDENTIFIED BY '$LAMP_USER_PASSWORD';"
#sudo -S <<< "$CIPASS" mysql -u root -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL ON lamp_database.* TO 'lamp_user'@'%';"
#sudo -S <<< "$CIPASS" mysql -u lamp_user -p"$LAMP_USER_PASSWORD" -e "CREATE TABLE lamp_database.rocket_parts_list (item_id INT AUTO_INCREMENT, content VARCHAR(255), PRIMARY KEY(item_id));"
#sudo -S <<< "$CIPASS" mysql -u lamp_user -p"$LAMP_USER_PASSWORD" -e "INSERT INTO lamp_database.rocket_parts_list (content) VALUES ('Fuel pump'),('Oxidizer pump'),('Heat exchanger');"
#REMOTE

#Install required software for SuiteCRM
echo "Install required software for Suitecrm"
add-apt-repository ppa:ondrej/php -y
apt-get update
apt-get install php$PHP_VERSION libapache2-mod-php$PHP_VERSION php$PHP_VERSION-common php$PHP_VERSION-mysql php$PHP_VERSION-gmp php$PHP_VERSION-curl \
php$PHP_VERSION-intl php$PHP_VERSION-mbstring php$PHP_VERSION-xmlrpc php$PHP_VERSION-gd php$PHP_VERSION-bcmath php$PHP_VERSION-imap \
php$PHP_VERSION-xml php$PHP_VERSION-cli php$PHP_VERSION-zip -y

#Update php.ini file with required settings
echo "update php file"
short_open_tag=On
memory_limit=256M
upload_max_filesize=100M
max_execution_time=360

for key in short_open_tag memory_limit upload_max_filesize max_execution_time
do
	sed -i "s/^\($key\).*/\1 $(eval echo = \${$key})/" /etc/php/$PHP_VERSION/apache2/php.ini
done

#Restart apache
echo "restart apahce"
systemctl restart apache2.service

#Test file created for debugging
echo "<?php phpinfo( ); ?>" | sudo tee /var/www/html/phpinfo.php

#Download and install latest SuiteCRM. Composer v2 does not work with Suitecrm.
echo "Download and install suitecrm files"
cd /tmp
file_url="<%= archives.link('Automation Training Archive', 'SuiteCRM-7.14.3.zip', 1200) %>"
wget $file_url -O "./SuiteCRM-7.14.3.zip" --no-check-certificate
apt-get install unzip -y
unzip /tmp/SuiteCRM-7.14.3.zip -d /var/www/html
mv /var/www/html/SuiteCRM-7.14.3/ /var/www/html/suitecrm
cd /var/www/html/suitecrm
chown -R www-data:www-data /var/www/html/suitecrm/
chmod -R 755 /var/www/html/suitecrm/